### ISSUE TITLE
Write unit tests for the methods implemented

### ISSUE THREAD

**Issue by DinisCruz** [joyrexus/func-js-book#1]
I think it would be very useful if some of the test code that is already on https://github.com/joyrexus/func-js-book/blob/master/coffee/1.coffee.md could be implemented as unittests

for example this is how I coded the existly and truthly tests https://github.com/o2platform/fluentnode/blob/master/test/globals.test.coffee

This would also allow the compare the JS version with the Coffee-Script version and confirm that they behave the same

**Comment by joyrexus** [comment]
The tests are intended primarily to demonstrate usage, so I hesitate to extract them or add any additional testing overhead.  For more complex constructs where more elaborate testing may be required, I might include separate tests (run with [tape](http://www.macwright.org/2014/03/11/tape-is-cool.html)), but I'd still include asserts within the literate file to demonstrate usage.

---

Re your **fluentnode** project, why not just use [underscore](http://underscorejs.org/) and [underscore-contrib](http://documentcloud.github.io/underscore-contrib/)? (See @fogus [on underscore-contrib](http://blog.fogus.me/2013/04/25/announcing-underscore-contrib/).) 

Note that by extending native prototypes you incur a lot of overhead and other potential issues.  While it's often fine to _selectively_ extend a native prototype for a particular use case or for explanatory purposes (as the resulting native-like syntax is nice), I think its something of an antipattern to extend them _en masse_ (as Prototype.js did) and import globally.

**Comment by DinisCruz** [comment]
Well I don't view those tests has overhead :), I view them as a way to confirm and document the behaviour of what is being explained

Although I like underscore I prefer the more fluent reading style and functional programming that can be done with **fluentnode** (which allows me to also have the same API syntax that I developed for C#'s [FluentSharp](https://github.com/o2platform/FluentSharp) ).

Regarding the overhead, I would like to run some benchmarks and see if it really makes a big impact (specially when compared with the large amount of code that is executed with all app's imports)

**Comment by joyrexus** [comment]
> Well I don't view those tests has overhead :), I view them as a way to confirm and document the behaviour of what is being explained

Yeah, I only meant that I wouldn't want to include comprehensive unit tests inside the literate code, since the literate code files are meant to be _expository_.  That is, the various assert statements you see are primarily intended to be expository aids (in addition to sanity checks).  Unit tests provide useful documentation of code behavior, but I see that as different than conceptual exposition.

Anyway, I'm not at all opposed to supplementing the expository code with TAP/tape tests as separate files and would happily take a PR for that.
